### PR TITLE
Feat: dividing line

### LINKED ISSUE #10: Add-dividing-line
## Problem Description
Add a separating line to distinguish between the player's ship HUD information and the area where the ship is displayed.

## Todo List

-   [ ] Modify the DrawManager to include a method for rendering a horizontal line.
-   [ ] Update the GameScreen class to call this new method and draw the separating line.
-   [ ] Ensure the line doesn't interfere with the gameplay area or other HUD elements.

## Feature Description
A horizontal line will be added to the game screen to visually separate the area containing the player's ship HUD information from the main gameplay area where the ship is displayed.

## Additional Information
The line should be subtle enough not to distract from gameplay but clear enough to provide a visual separation. Consider using a color that complements the existing UI elements. The exact position of the line may need to be adjusted based on the current layout of the HUD and gameplay area.

### PR DESCRIPTION
**Pull request by kojesung**
## What
This PR adds a separation line to distinguish between the player's ship and the HUD for a cleaner UI. It also includes a fix to the cleanBullets method after discovering that enemy bullets were passing below the line during development.

- Added a separation line to improve the visual clarity of the player's ship and HUD.
- Modified the cleanBullets method to prevent enemy bullets from passing through the HUD area.

## Why
The separation line enhances the UI by clearly distinguishing the player's ship from the HUD. The cleanBullets method was adjusted to ensure enemy bullets are correctly handled and do not interfere with the HUD display.

## Related Issue
Closes #10

## How to Test
1. Start the game.
2. Verify that the separation line between the player's ship and the HUD is visible.
3. Check if enemy bullets disappear correctly before reaching the HUD area.

## Screenshots

image

## Additional Information

Since the disappearance of bullets cannot be visually represented in the game screen, the relevant code is provided below.
image

### CODE REVIEW

**Comment by yunsful** [comment]
image

- The boundary line is correctly displayed at the bottom of the screen.
- Bullets are properly removed when they hit the bottom.

**Review by yunsful — APPROVED** [review]
image

- The boundary line is correctly displayed at the bottom of the screen.
- Bullets are properly removed when they hit the bottom.

**Review by DongWonLee2 — APPROVED** [review]
스샷

It was confirmed that it worked normally.
We will also discuss the color of the dividing line in the future and decide.

**Review by min5421 — APPROVED** [review]
I think it's really good to disappear before reaching the HUD area.

**Review by LeeHyunWoo02 — APPROVED** [review]
I've checked firsthand that the dividing line works without errors.

**Pull request merged**
