### PR TITLE
Feat: display bomb item

### LINKED ISSUE #36: Display-bomb-item
## Problem Description

When the player gets the bomb item, it is displayed on the game screen.

## Todo List

-   [ ] Modify a DrawManager.class
-   [ ] Modify a GameScreen.class

## Feature Description
When the player gets a bomb item, it displays the bomb  between the attack speed and the number of enemies. And when the player uses the bomb item, it removes the displayed bomb.

### PR DESCRIPTION
**Pull request by min5421**
## What
This PR display the bomb item. It includes the following changes:
- Add drawItem method in DrawManager class
- Call drawItem in GameScreen from DrawManager

## Why
To display the gained bomb item 

## Related Issue
Closes #36

## How to Test
1. Run the core class
2. Check if the bomb is displayed, when the player gets a bomb item.
3. Check if the displayed bomb is removed, when the player uses the bomb item.

## Screenshots
item

### CODE REVIEW

**Review by kojesung — APPROVED** [review]
image

- I have confirmed that when a bomb item is acquired, an item image is added to the bottom of the screen.
- I have verified that comments related to the author have been added."

**Review by DongWonLee2 — APPROVED** [review]
screenshot4

It was confirmed that it worked normally. Thank you for your hard work!

**Review by LeeHyunWoo02 — APPROVED** [review]
image

-> When you acquired the bomb, it was confirmed that it was displayed to the player.


image

-> When the acquired bomb item was used, it was fired safely and the enemy ships were also confirmed to explode.

**Review by aeioiie — APPROVED** [review]
image
I confirmed that when a bomb item is acquired, the bomb image appears well at the bottom of the left screen. LGTM!

**Review by yunsful — APPROVED** [review]
image

LGTM

**Review by sml-logs — APPROVED** [review]
I have confirmed if the bomb is displayed, when the player gets a bomb item.
I have confirmed if the displayed bomb is removed, when the player uses the bomb item.

I have confirmed that all functions are working well.
ScreenShot 2024-10-10 오후 4 50 30
ScreenShot 2024-10-10 오후 4 50 35

ScreenShot 2024-10-10 오후 4 50 41

**Pull request merged**
