### PR TITLE
HUD function development v1.0

### LINKED ISSUE #42: Modify-TopBottom-Background-Color
## Problem Description

Modify the background color of the upper part of the top green line and the lower part of the bottom green line.

## Todo List

-   [x] Change the color of the backgrounds to black.
-   [x] Modify the draw method of the GameScreen class.
-   [x] Add the drawRect method of the DrawManagerImpl class.

## Feature Description

The background color of the top and bottom will be modified to black for the better gameplay.

### PR DESCRIPTION
**Pull request by DongWonLee2**
## What
This PR adds new HUD functionalities and updates. It includes the following changes:
- Change background color around green lines.
- Fix bullet speed notation error.
- Feature add the status information of 2p.
- Change player ships colors.

## Why
- For better visibility, a black background has been applied to the status section.
- The bullet speed display code was modified by another team, which made it different from the previous HUD, so adjustments were made.
- To improve the HUD, a 2P status feature was added for two-player mode, and the ship's color was changed.
- The ship's color was matched with the heart color to enhance the HUD.

## Related Issue
Closes #42 #43 #46 #48 

## Screenshots
image
image

### CODE REVIEW

**Review by kojesung — APPROVED** [review]
image

image

LGTM

**Review by LeeHyunWoo02 — APPROVED** [review]
image

LGTM

**Review by min5421 — APPROVED** [review]
LGTM

**Review by yunsful — APPROVED** [review]
스크린샷 2024-10-20 오후 5 34 01

LGTM

**Review by aeioiie — APPROVED** [review]
image
LGTM

**Review by sml-logs — APPROVED** [review]
LGTM
ScreenShot 2024-10-20 오후 9 13 30
ScreenShot 2024-10-20 오후 9 16 07

**Pull request merged**
